#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
/usr/bin/feh --bg-fill /home/ardillamas/Descargas/pxfuel.jpg
sudo mount -o uid=ardillamas,gid=ardillamas -t ntfs-3g -o big_writes,noatime /dev/nvme0n1p4 /home/ardillamas/disk/
bspc rule -a Screenkey manage=off
/home/ardillamas/.config/polybar/launch.sh
picom &
rclone mount sqlboolean:sqlboolean ~/Escritorio/sqlboolean --vfs-cache-mode writes &
wmname LG3D &
xinput --set-prop "ELAN07C8:00 04F3:3298 Touchpad" "libinput Tapping Enabled" 1
xinput --set-prop "ELAN07C8:00 04F3:3298 Touchpad" "libinput Natural Scrolling Enabled" 1
xsetroot -cursor_name left_ptr
#bspc config border_width 0
